const GridAdjust = {
  opstions: {
    canFocus: true,
    range: true,
  },
  columns: [
    {
      prop: "index",
      name: "#",
      sortable: true,
      size: 60,
    },
    {
      prop: "operationType",
      name: "Tipo de Operação",
      sortable: true,
      size: 150,
    },
    {
      prop: "matriculation",
      name: "Matrícula",
      sortable: true,
      size: 90,
    },
    {
      prop: "client",
      name: "Cliente",
      sortable: true,
      size: 80,
    },
    {
      prop: "place",
      name: "Posto",
      sortable: true,
      size: 100,
    },
    {
      prop: "reason",
      name: "Motivo",
      sortable: true,
      size: 150,
    },
    {
      prop: "hedgingFeature",
      name: "Cobertura",
      sortable: true,
      size: 95,
    },
    {
      prop: "startDate",
      name: "Data Início",
      sortable: true,
      size: 110,
    },
    {
      prop: "endDate",
      name: "Data Fim",
      sortable: true,
      size: 110,
    },
    {
      prop: "enterTimeManually",
      name: "Inf. Horario Man.",
      sortable: true,
      size: 140,
    },
    {
      prop: "postCalculationProfile",
      name: "Posto Util. no Perfil de Apur.",
      sortable: true,
      size: 210,
    },
    {
      prop: "employeeHours",
      name: "Horario do Colaborador",
      size: 185,
    },
    {
      prop: "entry1",
      name: "Entrada",
      sortable: true,
      size: 80,
    },
    {
      prop: "departure1",
      name: "Saida",
      size: 70,
    },
    {
      prop: "entry2",
      name: "Entrada",
      size: 80,
    },
    {
      prop: "departure2",
      name: "Saida",
      size: 70,
    },
    {
      prop: "description",
      name: "Descrição",
      size: 270,
    },
  ],
  rows: [
    {
      operationType: "Cobertura de Posto",
      matriculation: "X000001",
      client: "TESTE NEXTI",
      place: "CC - SP - TESTE",
      reason: "Hora-Extra - Programada Faturada",
      hedgingFeature: "HORA EXTRA",
      startDate: "10/04/2022",
      endDate: "10/04/2022",
      enterTimeManually: "Não",
      postCalculationProfile: "",
      employeeHours: "IM|08:00-17:00",
      entry1: "",
      departure1: "",
      entry2: "",
      departure2: "",
      description: "Acerto Hora Extra - Autorizada",
    },
    {
      operationType: "Cobertura de Posto",
      matriculation: "X000001",
      client: "TESTE NEXTI",
      place: "CC - SP - TESTE",
      reason: "Hora-Extra - Programada Faturada",
      hedgingFeature: "FT",
      startDate: "10/04/2022",
      endDate: "10/04/2022",
      enterTimeManually: "Sim",
      postCalculationProfile: "",
      employeeHours: "",
      entry1: "07:00",
      departure1: "11:00",
      entry2: "12:00",
      departure2: "18:00",
      description: "Acerto Hora Extra - Autorizada",
    },
  ],
};

for (let i = 1; i < 1000; i++)
  GridAdjust.rows.push({
    operationType: "",
    matriculation: "",
    client: "",
    place: "",
    reason: "",
    hedgingFeature: "",
    startDate: "",
    endDate: "",
    enterTimeManually: "",
    postCalculationProfile: "",
    employeeHours: "",
    entry1: "",
    departure1: "",
    entry2: "",
    departure2: "",
    description: "",
  });

export default GridAdjust;
