const GridAdjust = {
  opstions: {
    canFocus: true,
    range: true,
  },
  columns: [
    {
      prop: "operationType",
      name: "Tipo de Operação",
      sortable: true,
    },
    {
      prop: "matriculation",
      name: "Matrícula",
      sortable: true,
    },
    {
      prop: "client",
      name: "Cliente",
      sortable: true,
      size: 120,
    },
    {
      prop: "place",
      name: "Posto",
      sortable: true,
      size: 120,
    },
    {
      prop: "reason",
      name: "Motivo",
      sortable: true,
      size: 120,
    },
    {
      prop: "hedgingFeature",
      name: "Recurso de Cobertura",
      sortable: true,
      size: 120,
    },
    {
      prop: "startDate",
      name: "Data Início",
      sortable: true,
      size: 120,
    },
    {
      prop: "endDate",
      name: "Data Fim",
      sortable: true,
      size: 120,
    },
    {
      prop: "enterTimeManually",
      name: "Inf. Horario Man.",
      sortable: true,
      size: 120,
    },
    {
      prop: "postCalculationProfile",
      name: "Posto Util. no Perfil de Apur.",
      sortable: true,
      size: 120,
    },
    {
      prop: "employeeHours",
      name: "Horario do Colaborador",
      size: 120,
    },
    {
      prop: "entry1",
      name: "Entrada",
      sortable: true,
      size: 120,
    },
    {
      prop: "departure1",
      name: "Saida",
      size: 120,
    },
    {
      prop: "entry2",
      name: "Entrada",
      size: 120,
    },
    {
      prop: "departure2",
      name: "Saida",
      size: 120,
    },
    {
      prop: "description",
      name: "Descrição",
      size: 120,
    },
  ],
  rows: [
    {
      operationType: "Cobertura de Posto",
      matriculation: "3089",
      client: "xxx",
      place: "XXX - YYY",
      reason: "Hora Extra - Autorizada Programada",
      hedgingFeature: "H6",
      startDate: "10/04/2022",
      endDate: "10/04/2022",
      enterTimeManually: "Não",
      postCalculationProfile: "",
      employeeHours: "IM|08:00-17:00",
      entry1: "",
      departure1: "",
      entry2: "",
      departure2: "",
      description: "Acerto Hora Extra - Autorizada",
    },
    {
      operationType: "Cobertura de Posto",
      matriculation: "789",
      client: "ZZZ",
      place: "ZZZ - AAA",
      reason: "Hora Extra - Autorizada Programada",
      hedgingFeature: "FT",
      startDate: "10/04/2022",
      endDate: "10/04/2022",
      enterTimeManually: "Sim",
      postCalculationProfile: "",
      employeeHours: "",
      entry1: "07:00",
      departure1: "11:00",
      entry2: "12:00",
      departure2: "18:00",
      description: "Acerto Hora Extra - Autorizada",
    },
  ],
};

for (let i = 1; i < 1000; i++)
  GridAdjust.rows.push({
    operationType: "",
    matriculation: "",
    client: "",
    place: "",
    reason: "",
    hedgingFeature: "",
    startDate: "",
    endDate: "",
    enterTimeManually: "",
    postCalculationProfile: "",
    employeeHours: "",
    entry1: "",
    departure1: "",
    entry2: "",
    departure2: "",
    description: "",
  });

export default GridAdjust;
