// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using Microsoft.Extensions.Options;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Interactions;
using OpenQA.Selenium.Support.UI;
using PoitAdjustRobotAPI.Core.Interface;

namespace PoitAdjustRobotAPI.Core.UseCases.Workshift
{
    public class Adjustment : IUseCase<bool>, IDisposable
    {
        public IWebDriver driver { get; private set; }
        public IDictionary<string, object> vars { get; private set; }
        public IJavaScriptExecutor js { get; private set; }
        public bool result { get; set; }
        ChromeOptions options = new ChromeOptions();

        public Adjustment()
        {

            options.AddArguments("--headless", "--window-size=1552,832", "--remote-debugging-port=4444");
            options.BinaryLocation = "/app/chromedriver";

            driver = new ChromeDriver(options);
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }

        public void Dispose()
        {
            driver.Quit();
        }

        public void DoWork()
        {
            driver.Navigate().GoToUrl("https://app.nexti.com/");
            driver.Manage().Window.Size = new System.Drawing.Size(980, 820);
            driver.FindElement(By.Id("inputDomain")).Click();
            driver.FindElement(By.Id("inputDomain")).SendKeys("grupooikos");
            driver.FindElement(By.Id("next-step")).Click();
            {
                WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(30));
                wait.Until(driver => driver.FindElement(By.Id("inputUsername")).Displayed);
            }
            {
                WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(30));
                wait.Until(driver => driver.FindElement(By.Id("inputUsername")).Enabled);
            }
            driver.FindElement(By.Id("inputUsername")).SendKeys("messias.teste");
            driver.FindElement(By.Id("inputPassword")).SendKeys("1234");
            driver.FindElement(By.CssSelector(".btn:nth-child(7)")).Click();
            driver.FindElement(By.CssSelector(".icon-filtro-")).Click();
            driver.FindElement(By.CssSelector(".siderbar2")).Click();
            {
                var element = driver.FindElement(By.CssSelector(".overscreen_child"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).ClickAndHold().Perform();
            }
            {
                var element = driver.FindElement(By.CssSelector(".overscreen_child"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
            }
            {
                var element = driver.FindElement(By.CssSelector(".overscreen_child"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Release().Perform();
            }
            driver.FindElement(By.CssSelector(".siderbar2")).Click();
            driver.FindElement(By.CssSelector(".hbox:nth-child(4) .textarea-config")).Click();
            {
                WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(30));
                wait.Until(driver => driver.FindElement(By.XPath("/html/body/core-main/div/searchfilter/div/div[1]/div[2]/div[2]/div/form/div[4]/div[4]/div[2]/nexti-textarea/div/textarea")).Enabled);
            }
            driver.FindElement(By.XPath("/html/body/core-main/div/searchfilter/div/div[1]/div[2]/div[2]/div/form/div[4]/div[4]/div[2]/nexti-textarea/div/textarea")).SendKeys("X000001");
            driver.FindElement(By.LinkText("Filtrar")).Click();
            driver.FindElement(By.CssSelector(".padding-top > .person_text:nth-child(2)")).Click();
            js.ExecuteScript("window.scrollTo(0,0)");
            driver.FindElement(By.CssSelector(".row_day:nth-child(5) .col:nth-child(6)")).Click();
            driver.FindElement(By.CssSelector(".timepicker:nth-child(1)")).Click();
            driver.FindElement(By.CssSelector(".flatpickr-hour")).Click();
            driver.FindElement(By.CssSelector(".flatpickr-hour")).SendKeys("012");
            driver.FindElement(By.CssSelector(".flatpickr-minute")).Click();
            driver.FindElement(By.CssSelector(".flatpickr-minute")).SendKeys("030");
            driver.FindElement(By.CssSelector(".clocking-adjustment-one:nth-child(2)")).Click();
            {
                var dropdown = driver.FindElement(By.Id("select2-aafx-container"));
                dropdown.FindElement(By.XPath("//option[. = 'Outros']")).Click();
            }
            driver.FindElement(By.Id("note")).Click();
            driver.FindElement(By.Id("note")).SendKeys("Politica da empresa");
            driver.FindElement(By.LinkText("Confirmar")).Click();
            driver.FindElement(By.CssSelector(".siderbar2")).Click();
        }
    }
}